from environs import Env

env = Env()
env.read_env()

JSON_WITH_PHRASES = "https://bit.ly/3mNQr8T"
DIALOG_FLOW_PROJECT_ID = env.str("DIALOG_FLOW_PROJECT_ID")
DIALOG_FLOW_SESSION_ID = env.str("DIALOG_FLOW_SESSION_ID")
GOOGLE_APPLICATION_CREDENTIALS = env.str("GOOGLE_APPLICATION_CREDENTIALS")
TG_DIALOG_BOT_API_TOKEN = env.str("TG_DIALOG_BOT_API_TOKEN")
TG_LOGS_BOT_API_TOKEN = env.str("TG_LOGS_BOT_API_TOKEN")
TG_USER_CHAT_ID = env.str("TG_USER_CHAT_ID")
VK_TOKEN = env.str("VK_TOKEN")
