import os

from dotenv import load_dotenv

load_dotenv()

TG_DIALOG_BOT_API_TOKEN = os.getenv("TG_DIALOG_BOT_API_TOKEN")
TG_LOGS_BOT_API_TOKEN = os.getenv("TG_LOGS_BOT_API_TOKEN")
TG_USER_CHAT_ID = os.getenv("TG_USER_CHAT_ID")
DIALOG_FLOW_PROJECT_ID = os.getenv("DIALOG_FLOW_PROJECT_ID")
DIALOG_FLOW_SESSION_ID = os.getenv("DIALOG_FLOW_SESSION_ID")
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
VK_TOKEN = os.getenv("VK_TOKEN")
